apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    name: {{ .Values.name }}
    digi.dev/type: kernel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagepull }}
          env:
          - name: GROUP
            value: {{ .Values.group }}
          - name: VERSION
            value: {{ .Values.version }}
          - name: PLURAL
            value: {{ .Values.plural }}
          - name: NAME
            value: {{ .Values.name }}
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          - name: MOUNTER
            value: {{ quote .Values.mounter }}
          - name: LOGLEVEL
            value: {{ .Values.log_level | default "20" | quote }}
          - name: LAKE_PROVIDER
            value: {{ .Values.lake_provider | default "zed" }}
          - name: LAKE
            value: {{ .Values.lake | default "http://lake:6534" }}
          - name: ZED_LAKE # for backward compatibility TBD deprecate in v0.3
            value: {{ .Values.zed_lake | default "http://lake:6534" }}
          ports:
          - containerPort: 9867

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
    digi.dev/type: kernel
spec:
  ports:
  - port: 6534 # lake
    targetPort: 9867
    protocol: TCP
  selector:
    name: {{ .Values.name }}
